### ISSUE TITLE
can’t build with openssl1.1.1a without deprecated api

### ISSUE THREAD

**Issue by dimatto** [SoftEtherVPN/SoftEtherVPN#864]
please get rid of deprecated api

**Comment by solipse** [comment]
Need more information to repeat build error.

**Comment by chipitsine** [comment]
can you provide details why that api is deprecated ?

**Comment by updatede** [comment]
While build openssl 1.1.1a with no-deprecated and use it as library to build softethervpn, there's lot of "implicit declaration" warnings and "undeclared" errors, can't pass compiling, when compiling openssl without no-deprecated, softethervpn can pass compiling, but not good for always using deprecated api since other application remove them and someday they will be removed from openssl library :
```
In file included from /updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/./Mayaqua/Mayaqua.h:266:0,
                 from /updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:146:
/updatede/sdk/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^~~~~~~
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'RsaPublicToBuf':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:749:2: warning: implicit declaration of function 'RSA_get0_key'; did you mean 'DH_get0_key'? [-Wimplicit-function-declaration]
  RSA_get0_key(rsa, &n, NULL, NULL);
  ^~~~~~~~~~~~
  DH_get0_key
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'BinToBigNum':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:833:7: warning: implicit declaration of function 'BN_new'; did you mean 'DH_new'? [-Wimplicit-function-declaration]
  bn = BN_new();
       ^~~~~~
       DH_new
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:833:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  bn = BN_new();
     ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:834:2: warning: implicit declaration of function 'BN_bin2bn'; did you mean 'OBJ_nid2sn'? [-Wimplicit-function-declaration]
  BN_bin2bn(data, size, bn);
  ^~~~~~~~~
  OBJ_nid2sn
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'BigNumToBuf':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:851:9: warning: implicit declaration of function 'BN_num_bytes'; did you mean 'RAND_bytes'? [-Wimplicit-function-declaration]
  size = BN_num_bytes(bn);
         ^~~~~~~~~~~~
         RAND_bytes
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:853:2: warning: implicit declaration of function 'BN_bn2bin'; did you mean 'OBJ_sn2nid'? [-Wimplicit-function-declaration]
  BN_bn2bin(bn, tmp);
  ^~~~~~~~~
  OBJ_sn2nid
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'OpenSSL_InitLock':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:870:17: warning: implicit declaration of function 'CRYPTO_num_locks'; did you mean 'CRYPTO_realloc'? [-Wimplicit-function-declaration]
  ssl_lock_num = CRYPTO_num_locks();
                 ^~~~~~~~~~~~~~~~
                 CRYPTO_realloc
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:878:2: warning: implicit declaration of function 'CRYPTO_set_locking_callback'; did you mean 'BIO_set_info_callback'? [-Wimplicit-function-declaration]
  CRYPTO_set_locking_callback(OpenSSL_Lock);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  BIO_set_info_callback
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:879:2: warning: implicit declaration of function 'CRYPTO_set_id_callback'; did you mean 'BIO_set_callback'? [-Wimplicit-function-declaration]
  CRYPTO_set_id_callback(OpenSSL_Id);
  ^~~~~~~~~~~~~~~~~~~~~~
  BIO_set_callback
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'OpenSSL_Lock':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:903:13: error: 'CRYPTO_LOCK' undeclared (first use in this function); did you mean 'CRYPTO_RWLOCK'?
  if (mode & CRYPTO_LOCK)
             ^~~~~~~~~~~
             CRYPTO_RWLOCK
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:903:13: note: each undeclared identifier is reported only once for each function it appears in
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'NewX509':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1746:7: warning: implicit declaration of function 'X509_get_notBefore'; did you mean 'X509_getm_notBefore'? [-Wimplicit-function-declaration]
  t1 = X509_get_notBefore(x509);
       ^~~~~~~~~~~~~~~~~~
       X509_getm_notBefore
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1746:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  t1 = X509_get_notBefore(x509);
     ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1747:7: warning: implicit declaration of function 'X509_get_notAfter'; did you mean 'X509_getm_notAfter'? [-Wimplicit-function-declaration]
  t2 = X509_get_notAfter(x509);
       ^~~~~~~~~~~~~~~~~
       X509_getm_notAfter
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1747:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  t2 = X509_get_notAfter(x509);
     ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'NewRootX509':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1888:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  t1 = X509_get_notBefore(x509);
     ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:1889:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  t2 = X509_get_notAfter(x509);
     ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'RsaVerifyEx':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2323:6: warning: implicit declaration of function 'RSA_public_decrypt'; did you mean 'DES_pcbc_encrypt'? [-Wimplicit-function-declaration]
  if (RSA_public_decrypt(bits / 8, sign, decrypt_data, EVP_PKEY_get0_RSA(k->pkey), RSA_PKCS1_PADDING) <= 0)
      ^~~~~~~~~~~~~~~~~~
      DES_pcbc_encrypt
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2323:83: error: 'RSA_PKCS1_PADDING' undeclared (first use in this function); did you mean 'i2d_PKCS12_SAFEBAG'?
  if (RSA_public_decrypt(bits / 8, sign, decrypt_data, EVP_PKEY_get0_RSA(k->pkey), RSA_PKCS1_PADDING) <= 0)
                                                                                   ^~~~~~~~~~~~~~~~~
                                                                                   i2d_PKCS12_SAFEBAG
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'RsaSignEx':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2364:6: warning: implicit declaration of function 'RSA_private_encrypt'; did you mean 'AES_bi_ige_encrypt'? [-Wimplicit-function-declaration]
  if (RSA_private_encrypt(sizeof(hash), hash, dst, EVP_PKEY_get0_RSA(k->pkey), RSA_PKCS1_PADDING) <= 0)
      ^~~~~~~~~~~~~~~~~~~
      AES_bi_ige_encrypt
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2364:79: error: 'RSA_PKCS1_PADDING' undeclared (first use in this function); did you mean 'i2d_PKCS12_SAFEBAG'?
  if (RSA_private_encrypt(sizeof(hash), hash, dst, EVP_PKEY_get0_RSA(k->pkey), RSA_PKCS1_PADDING) <= 0)
                                                                               ^~~~~~~~~~~~~~~~~
                                                                               i2d_PKCS12_SAFEBAG
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'RsaCheck':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2425:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  e = BN_new();
    ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2426:8: warning: implicit declaration of function 'BN_set_word'; did you mean 'rl_set_mark'? [-Wimplicit-function-declaration]
  ret = BN_set_word(e, RSA_F4);
        ^~~~~~~~~~~
        rl_set_mark
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2426:23: error: 'RSA_F4' undeclared (first use in this function); did you mean 'RSA'?
  ret = BN_set_word(e, RSA_F4);
                       ^~~~~~
                       RSA
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2429:3: warning: implicit declaration of function 'BN_free'; did you mean 'rl_free'? [-Wimplicit-function-declaration]
 BN_free(e);
   ^~~~~~~
   rl_free
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2437:9: warning: implicit declaration of function 'RSA_new'; did you mean 'SSL_new'? [-Wimplicit-function-declaration]
   rsa = RSA_new();
         ^~~~~~~
         SSL_new
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2437:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   rsa = RSA_new();
       ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2438:9: warning: implicit declaration of function 'RSA_generate_key_ex'; did you mean 'DH_generate_key'? [-Wimplicit-function-declaration]
   ret = RSA_generate_key_ex(rsa, bit, e, NULL);
         ^~~~~~~~~~~~~~~~~~~
         DH_generate_key
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2470:2: warning: implicit declaration of function 'RSA_free'; did you mean 'SSL_free'? [-Wimplicit-function-declaration]
  RSA_free(rsa);
  ^~~~~~~~
  SSL_free
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'RsaGen':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2508:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  e = BN_new();
    ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2509:23: error: 'RSA_F4' undeclared (first use in this function); did you mean 'RSA'?
  ret = BN_set_word(e, RSA_F4);
                       ^~~~~~
                       RSA
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:2520:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   rsa = RSA_new();
       ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'FreeCryptLibrary':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3815:2: warning: implicit declaration of function 'EVP_cleanup'; did you mean 'EVP_PBE_cleanup'? [-Wimplicit-function-declaration]
  EVP_cleanup();
  ^~~~~~~~~~~
  EVP_PBE_cleanup
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3819:2: warning: implicit declaration of function 'ERR_free_strings'; did you mean 'ERR_load_strings'? [-Wimplicit-function-declaration]
  ERR_free_strings();
  ^~~~~~~~~~~~~~~~
  ERR_load_strings
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'InitCryptLibrary':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3833:2: warning: implicit declaration of function 'SSL_library_init'; did you mean 'SSL_in_init'? [-Wimplicit-function-declaration]
  SSL_library_init();
  ^~~~~~~~~~~~~~~~
  SSL_in_init
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3835:2: warning: implicit declaration of function 'OpenSSL_add_all_ciphers'; did you mean 'SSL_CTX_get_ciphers'? [-Wimplicit-function-declaration]
  OpenSSL_add_all_ciphers();
  ^~~~~~~~~~~~~~~~~~~~~~~
  SSL_CTX_get_ciphers
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3836:2: warning: implicit declaration of function 'OpenSSL_add_all_digests' [-Wimplicit-function-declaration]
  OpenSSL_add_all_digests();
  ^~~~~~~~~~~~~~~~~~~~~~~
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3837:2: warning: implicit declaration of function 'ERR_load_crypto_strings'; did you mean 'ERR_load_X509V3_strings'? [-Wimplicit-function-declaration]
  ERR_load_crypto_strings();
  ^~~~~~~~~~~~~~~~~~~~~~~
  ERR_load_X509V3_strings
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:3838:2: warning: implicit declaration of function 'SSL_load_error_strings'; did you mean 'ERR_lib_error_string'? [-Wimplicit-function-declaration]
  SSL_load_error_strings();
  ^~~~~~~~~~~~~~~~~~~~~~
  ERR_lib_error_string
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'DhNew':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:4428:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  dhg = BN_new();
      ^
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c: In function 'Internal_HMac':
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:4505:27: warning: passing argument 3 of 'MdProcess' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  len = MdProcess(m, dest, src, src_size);
                           ^~~
/updatede/sdk/build_dir/target-mipsel_24kc_musl/softethervpn5-5.01.9667/src/Mayaqua/Encrypt.c:456:6: note: expected 'void *' but argument is of type 'const void *'
 UINT MdProcess(MD *md, void *dest, void *src, UINT size)
      ^~~~~~~~~

```

**Comment by chipitsine** [comment]
thank you, it makes sense

**Comment by macvk** [comment]
I  see here no deprecated functions.

**Comment by chipitsine** [comment]
fixed in https://github.com/SoftEtherVPN/SoftEtherVPN/pull/943
