### ISSUE TITLE
Compiling failed on master branch, revision  478270efba7454c2049c6221f1ee6d9f5ec7e31b

### ISSUE THREAD

**Issue by tidatida** [SoftEtherVPN/SoftEtherVPN#488]
revision:  478270efba7454c2049c6221f1ee6d9f5ec7e31b

softethervpn\src\SEVPN.sln" (Rebuild target) (1) ->
(Mayaqua:Rebuild target) ->
  .\Network.c(5836): error C2143: 语法错误 : 缺少“;”(在“const”的前面)
  .\Network.c(5837): error C2065: “msg”: 未声明的标识符
  .\Network.c(5838): error C2065: “msg”: 未声明的标识符
  .\Network.c(5858): error C2143: 语法错误 : 缺少“{”(在“*”的前面)
  .\Network.c(5859): error C2371: “NewSslPipe”: 重定义；不同的基类型

    4 Warning(s)
    5 Error(s)

**Comment by davidebeatrici** [comment]
Thank you very much for the report.

The failure is caused by commit 83295bb736d282940a79f0bd2c1a4e45910101cf.

We didn't know it would cause issues with MSVC, as we only have Continuous Integration tests with GCC and Clang (Linux), unfortunately.

**Comment by chipitsine** [comment]
We need app veyor

If nobody submit a patch, than I'll do

**Comment by davidebeatrici** [comment]
Which software are you planning to use on AppVeyor?

**Comment by chipitsine** [comment]
Current VS image

**Comment by davidebeatrici** [comment]
We have to make the code compatible with Visual Studio 2017 first.

**Comment by chipitsine** [comment]
Uh-huh

**Comment by tidatida** [comment]
It sounds interesting compatible with Visual Studio 2017.

**Comment by macvk** [comment]
Guys, are you really programmers ? The error is here
Network.c -> Line 5836  -> const char *msg
this peace of code must be corrected
```
if (!preverify_ok)
{
			const char *msg = X509_verify_cert_error_string(clientcert->PreverifyErr);
			clientcert->PreverifyErr = X509_STORE_CTX_get_error(ctx);
			StrCpy(clientcert->PreverifyErrMessage, PREVERIFY_ERR_MESSAGE_SIZE, msg);
			Debug("SslCertVerifyCallback preverify error: '%s'\n", msg);
```
declaration must be placed after "{".

I am shocked... are you really sure that migration to vs2017 is necessary?

**Comment by davidebeatrici** [comment]
I meant that we have to make the code compatible with Visual Studio 2017 in order to use the current AppVeyor image.

**Comment by davidebeatrici** [comment]
@tidatida I created a pull request which should fix the compile problem.

Could you test it out, please?

**Comment by tidatida** [comment]
@davidebeatrici   remove msvc compiling errors #491  
Please see PR 491, it passed msvc compiling.

**Comment by moatazelmasry2** [comment]
Daiuyy wrote in the developers guide, that he wishes the code to remain compatible to vc 2008
https://github.com/SoftEtherVPN/SoftEtherVPN/wiki/SoftEther-VPN-Developers-Guideline-(DRAFT)

**Comment by davidebeatrici** [comment]
Depending on the issues showing up in Visual Studio 2017, we could create a separate project file for it while maintaining the code compatible with Visual Studio 2008.

**Comment by moatazelmasry2** [comment]
The problem is how in the world can we automate this kind of comoilation in travis-ci?

**Comment by davidebeatrici** [comment]
We have to use two separated build configurations on AppVeyor.

**Comment by moatazelmasry2** [comment]
Didn't know about that. It looks quite nice, will definitely try adding it to SE

**Comment by davidebeatrici** [comment]
I'm working on it.

**Comment by chipitsine** [comment]
@davidebeatrici , you can get it faster than me ))

I'm a bit busy, hope to find time in next couple of weeks for app veyor

**Comment by davidebeatrici** [comment]
@chipitsine No problem.

**Comment by davidebeatrici** [comment]
@moatazelmasry2 @chipitsine

Done: #498

**Comment by chipitsine** [comment]
Nice.

I would add artifacts, it is good for "here's link to test binaries"
