### ISSUE TITLE
Error build in OpenBSD

### ISSUE THREAD

**Issue by solipse** [SoftEtherVPN/SoftEtherVPN#1341]
SoftEther version: 5.01 Build 9674
Component: Server
Operating system: OpenBSD 6.9
Architecture: 64 bit

```c
[  4%] Built target libhamcore
[  7%] Built target hamcorebuilder
[  8%] Built target hamcore-archive-build
[  9%] Building C object src/Cedar/CMakeFiles/cedar.dir/Account.c.o
In file included from /home/SoftEtherVPN/src/Cedar/Account.c:10:
In file included from /home/SoftEtherVPN/src/Cedar/Hub.h:12:
In file included from /home/SoftEtherVPN/src/Cedar/Logging.h:11:
In file included from /home/SoftEtherVPN/src/Cedar/Cedar.h:14:
/home/SoftEtherVPN/src/./Mayaqua/Network.h:233:2: error: unknown type name 'pthread_t'
        pthread_t CallingThread;        // Thread that is calling the system call
        ^
1 error generated.
*** Error 1 in . (src/Cedar/CMakeFiles/cedar.dir/build.make:82 'src/Cedar/CMakeFiles/cedar.dir/Account.c.o': cd /home/SoftEtherVPN/build/src...)
*** Error 2 in . (CMakeFiles/Makefile2:328 'src/Cedar/CMakeFiles/cedar.dir/all': make -s -f src/Cedar/CMakeFiles/cedar.dir/build.make src/Ce...)
*** Error 2 in /home/SoftEtherVPN/build (Makefile:171 'all': make -s -f CMakeFiles/Makefile2 all)
```

**Comment by davidebeatrici** [comment]
Could you change https://github.com/SoftEtherVPN/SoftEtherVPN/blob/60568da9b720759e3fb244061b59e2570f9c19a3/src/Mayaqua/Network.h#L14-L16 to
```c
#ifdef OS_UNIX
#include <netinet/in.h>
#include <pthread.h>
#endif
```

and let me know whether it works, please?

**Comment by solipse** [comment]
/home/SoftEtherVPN/src/Cedar/BridgeUnix.c:28:10: fatal error: 'net/ethernet.h' file not found
#include <net/ethernet.h>
         ^~~~~~~~~~~~~~~~

**Comment by davidebeatrici** [comment]
Try to simply remove the include.

If it doesn't work, try to include `<netinet/if_ether.h>`.

**Comment by chipitsine** [comment]
are you trying to build from source ?

on OpenBSD there's ports collection. I know it is not possible to build latest master (only releases), but ports collection usually provides local distro patches.

from our side, it may be good activity to backport such patches if they exist

**Comment by davidebeatrici** [comment]
The compile failure is probably due to #1319.

**Comment by solipse** [comment]
Build from source. In OpenBSD ports collection no softether. Probably go to FreeBSD.

When remove the include net/ethernet.h:

Build from sour[ 67%] Building C object src/Mayaqua/CMakeFiles/mayaqua.dir/DNS.c.o
/home/SoftEtherVPN/src/Mayaqua/DNS.c:34:17: warning: passing 'const char *const' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return StrCmpi(c1->Hostname, c2->Hostname);
                       ^~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:43:19: note: passing argument to parameter 'str1' here
int StrCmpi(char *str1, char *str2);
                  ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:34:31: warning: passing 'const char *const' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return StrCmpi(c1->Hostname, c2->Hostname);
                                     ^~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:43:31: note: passing argument to parameter 'str2' here
int StrCmpi(char *str1, char *str2);
                              ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:47:9: warning: passing 'BYTE const[16]' to parameter of type 'void *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return CmpIpAddr(&c1->IP, &c2->IP);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:85:36: note: expanded from macro 'CmpIpAddr'
#define CmpIpAddr(ip1, ip2)                     (Cmp((ip1)->address, (ip2)->address, sizeof((ip1)->address)))
                                                     ^~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:186:15: note: passing argument to parameter 'p1' here
int Cmp(void *p1, void *p2, UINT size);
              ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:47:9: warning: passing 'BYTE const[16]' to parameter of type 'void *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        return CmpIpAddr(&c1->IP, &c2->IP);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:85:52: note: expanded from macro 'CmpIpAddr'
#define CmpIpAddr(ip1, ip2)                     (Cmp((ip1)->address, (ip2)->address, sizeof((ip1)->address)))
                                                                     ^~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:186:25: note: passing argument to parameter 'p2' here
int Cmp(void *p1, void *p2, UINT size);
                        ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:123:49: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (DnsCacheIsEnabled() == false || IsEmptyStr(hostname))
                                                       ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:97:23: note: passing argument to parameter 'str' here
bool IsEmptyStr(char *str);
                      ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:143:49: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (DnsCacheIsEnabled() == false || IsEmptyStr(hostname))
                                                       ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:97:23: note: passing argument to parameter 'str' here
bool IsEmptyStr(char *str);
                      ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:170:31: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                entry->Hostname = CopyStr(hostname);
                                                          ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:80:21: note: passing argument to parameter 'str' here
char *CopyStr(char *str);
                    ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:179:9: warning: passing 'BYTE const[16]' to parameter of type 'void *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                if (CmpIpAddr(&entry->IPv6, ipv6) != 0)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:85:52: note: expanded from macro 'CmpIpAddr'
#define CmpIpAddr(ip1, ip2)                     (Cmp((ip1)->address, (ip2)->address, sizeof((ip1)->address)))
                                                                     ^~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:186:25: note: passing argument to parameter 'p2' here
int Cmp(void *p1, void *p2, UINT size);
                        ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:181:25: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                        Copy(&entry->IPv6, ipv6, sizeof(entry->IPv6));
                                                           ^~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:186:9: warning: passing 'BYTE const[16]' to parameter of type 'void *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                if (CmpIpAddr(&entry->IPv4, ipv4) != 0)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:85:52: note: expanded from macro 'CmpIpAddr'
#define CmpIpAddr(ip1, ip2)                     (Cmp((ip1)->address, (ip2)->address, sizeof((ip1)->address)))
                                                                     ^~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:186:25: note: passing argument to parameter 'p2' here
int Cmp(void *p1, void *p2, UINT size);
                        ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:188:25: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                        Copy(&entry->IPv4, ipv4, sizeof(entry->IPv4));
                                                           ^~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:210:15: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                Copy(&t.IP, ip, sizeof(t.IP));
                            ^~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:220:47: warning: incompatible pointer types passing 'const IP **'
      (aka 'const struct IP **') to parameter of type 'IP *' (aka 'struct IP *') [-Wincompatible-pointer-types]
        if (DnsCacheIsEnabled() == false || IsZeroIP(&ip))
                                                     ^~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:1154:19: note: passing argument to parameter 'ip' here
bool IsZeroIP(IP *ip);
                  ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:230:15: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                Copy(&t.IP, ip, sizeof(t.IP));
                            ^~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:233:18: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                if (IsEmptyStr(hostname))
                               ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:97:23: note: passing argument to parameter 'str' here
bool IsEmptyStr(char *str);
                      ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:247:22: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                Copy(&entry->IP, ip, sizeof(entry->IP));
                                                 ^~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:254:32: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                        if (StrCmp(entry->Hostname, hostname) != 0)
                                                    ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:42:30: note: passing argument to parameter 'str2' here
int StrCmp(char *str1, char *str2);
                             ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:257:31: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                entry->Hostname = CopyStr(hostname);
                                                          ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:80:21: note: passing argument to parameter 'str' here
char *CopyStr(char *str);
                    ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:268:51: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if ((ipv6 == NULL && ipv4 == NULL) || IsEmptyStr(hostname))
                                                         ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:97:23: note: passing argument to parameter 'str' here
bool IsEmptyStr(char *str);
                      ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:273:14: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (StrCmpi(hostname, "localhost") == 0)
                    ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:43:19: note: passing argument to parameter 'str1' here
int StrCmpi(char *str1, char *str2);
                  ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:281:19: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (StrToIP(&ip, hostname))
                         ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:1034:28: note: passing argument to parameter 'str' here
bool StrToIP(IP *ip, char *str);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:379:13: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        Copy(ipv6, &cached->IPv6, sizeof(IP));
                   ^~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:380:13: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        Copy(ipv4, &cached->IPv4, sizeof(IP));
                   ^~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:401:19: error: use of undeclared identifier 'AI_ALL'
        hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;
                         ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:401:44: error: use of undeclared identifier 'AI_V4MAPPED'
        hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;
                                                  ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:413:21: warning: passing 'const struct in6_addr *' to parameter of type
      'struct in6_addr *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                        InAddrToIP6(&ip, &in->sin6_addr);
                                         ^~~~~~~~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:1031:43: note: passing argument to parameter 'addr' here
void InAddrToIP6(IP *ip, struct in6_addr *addr);
                                          ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:441:43: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'IP *' (aka 'struct IP *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (dst == NULL || size == 0 || IsZeroIP(ip))
                                                 ^~
/home/SoftEtherVPN/src/Mayaqua/./Network.h:1154:19: note: passing argument to parameter 'ip' here
bool IsZeroIP(IP *ip);
                  ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:468:21: warning: passing 'const IP *' (aka 'const struct IP *') to parameter of type
      'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        Copy(&resolver.IP, ip, sizeof(resolver.IP));
                           ^~
/home/SoftEtherVPN/src/Mayaqua/./Memory.h:184:28: note: passing argument to parameter 'src' here
void Copy(void *dst, void *src, UINT size);
                           ^
/home/SoftEtherVPN/src/Mayaqua/DNS.c:558:31: warning: passing 'const char *' to parameter of type 'char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (ip == NULL || IsEmptyStr(hostname))
                                     ^~~~~~~~
/home/SoftEtherVPN/src/Mayaqua/./Str.h:97:23: note: passing argument to parameter 'str' here
bool IsEmptyStr(char *str);
                      ^
27 warnings and 2 errors generated.
*** Error 1 in . (src/Mayaqua/CMakeFiles/mayaqua.dir/build.make:95 'src/Mayaqua/CMakeFiles/mayaqua.dir/DNS.c.o': cd /home/SoftEtherVPN/build...)
*** Error 2 in . (CMakeFiles/Makefile2:355 'src/Mayaqua/CMakeFiles/mayaqua.dir/all': make -s -f src/Mayaqua/CMakeFiles/mayaqua.dir/build.mak...)
*** Error 2 in /home/SoftEtherVPN/build (Makefile:171 'all': make -s -f CMakeFiles/Makefile2 all)
ce.

**Comment by chipitsine** [comment]
I installed openbsd-6.9 on vm.
issue is reproduced

**Comment by chipitsine** [comment]
```
/root/softethervpn/src/Mayaqua/DNS.c:401:19: error: use of undeclared identifier 'AI_ALL'
        hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;
                         ^
/root/softethervpn/src/Mayaqua/DNS.c:401:44: error: use of undeclared identifier 'AI_V4MAPPED'
        hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;
          
```

**Comment by davidebeatrici** [comment]
Looks like OpenBSD doesn't provide the two options:
https://github.com/openbsd/src/blob/04cba2782569480bf9984595088841a5df534b13/include/netdb.h#L158-L169

Solution:
```c
#ifndef AI_ALL
#define AI_ALL 0
#endif

#ifndef AI_V4MAPPED
#define AI_V4MAPPED 0
#endif
```

**Comment by chipitsine** [comment]
@davidebeatrici , I tested those ifndef-s, they definetly fixes build.
can you please create a PR (I do not know where to place them properly)

**Comment by axot** [comment]
I got the same error in lib-musl.

```
In file included from /SoftEtherVPN/src/Cedar/Cedar.h:14,
                 from /SoftEtherVPN/src/Cedar/Logging.h:11,
                 from /SoftEtherVPN/src/Cedar/Hub.h:12,
                 from /SoftEtherVPN/src/Cedar/Account.c:10:
/SoftEtherVPN/src/./Mayaqua/Network.h:237:2: error: unknown type name 'pthread_t'
  237 |  pthread_t CallingThread; // Thread that is calling the system call
      |  ^~~~~~~~~
make[2]: *** [src/Cedar/CMakeFiles/cedar.dir/build.make:82: src/Cedar/CMakeFiles/cedar.dir/Account.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: src/Cedar/CMakeFiles/cedar.dir/all] Error 2
make[2]: Leaving directory '/SoftEtherVPN/build'
make[1]: Leaving directory '/SoftEtherVPN/build'
make: *** [Makefile:171: all] Error 2
```

Here is the Dockerfile which I'm testing.
```
FROM alpine:3.13 as build
MAINTAINER axot

ENV USE_MUSL=YES
ENV VERSION=5.02.0

RUN set -eux \
  && apk add --no-cache \
    binutils         \
    cmake            \
    build-base       \
    readline-dev     \
    openssl-dev      \
    ncurses-dev      \
    libsodium-dev    \
    cmake            \
    gnu-libiconv     \
    zlib-dev         \
    git              \
  && git clone -b ${VERSION} https://github.com/SoftEtherVPN/SoftEtherVPN.git \
  && cd SoftEtherVPN \
  && git submodule init \
  && git submodule update \
  && ./configure \
  && make -C build \
  && make -C build install
```
