### PR TITLE
remove msvc compiling errors

### PR DESCRIPTION
**Pull request by moatazelmasry2**
Changes proposed in this pull request:
 Fixex MSVC Errors caused by Commit 478270ef

The error thrown by msvc (translated from chinese):
```
.\Network.c(5836): error C2143: Syntax error : Missing ";" (in front of "const")
.\Network.c(5837): error C2065: "msg": undeclared identifier
.\Network.c(5838): error C2065: "msg": undeclared identifier
.\Network.c(5858): error C2143: Syntax error : Missing "{" (before "*")
.\Network.c(5859): error C2371: "NewSslPipe": redefine; different base types
``` 

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- 1

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Unfortunately his commit email is not the same as his GitHub one, meaning that it will not be counted as contribution.

I would manually change it, along with the name: `git commit --amend --author="tinyserver <tinyserver@foxmail.com>"`.
