### ISSUE TITLE
Softether VPN doesn't compile on Ubuntu 13.10 64bit

### ISSUE THREAD

**Issue by nonammm** [SoftEtherVPN/SoftEtherVPN#28]
Softether VPN doesn't compile on Ubuntu 13.10 64bit
Error:
gcc -DNDEBUG -DVPN_SPEED -DUNIX -DUNIX_LINUX -DCPU_64 -D_REENTRANT -DREENTRANT -D_THREAD_SAFE -D_THREADSAFE -DTHREAD_SAFE -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -I./src/ -I./src/Cedar/ -I./src/Mayaqua/ -O2 -fsigned-char -m64 -c src/Mayaqua/Cfg.c -o tmp/objs/Mayaqua/Cfg.o
In file included from src/Mayaqua/Cfg.c:104:0:
./src/Mayaqua/Mayaqua.h:257:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
make: **\* [tmp/objs/Mayaqua/Cfg.o] Error 1

Steps to reproduce:
1) sudo apt-get install gcc binutils tar gzip zlibc openssl libreadline6 libncurses5 libpthread-stubs0 libpthread-workqueue0 git libssl1.0.0 libcrypto++9 checkinstall
2) git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
3) ./configure
4) make
