### PR TITLE
OpenVPN client certificate authentication (Individual Certificate Authentication)

### LINKED ISSUE #55: Help please with OpenVPN client + certificates authorization
Hello. Came here to ask to solve my problem.
System: FreeBSD 9.2 x64, CentOS 6.5 x64, Ubuntu 14.04 x64 (tried all of them)
Client: Windows XP SP3 openvpn-install-2.3.4-I001-i686
SoftEther VPN Server 4.06 Build 9437

I am trying to authorise users without password, just by certificates(with OpenVPN client). Made CA certificate, installed to SoftEther, made certificate for client, added to .ovpn file and to softether. But when I try to connect always getting error:

Sun May 25 00:00:00 2014 us=15625 AUTH: Received control message: AUTH_FAILED
Sun May 25 00:00:00 2014 us=15625 TCP/UDP: Closing socket

Password auth works like a charm!

So maybe somebody figured that problem? Or how to make it work.

Logs:
http://pastebin.com/crgs6PVa
http://pastebin.com/n3qB06EH
http://pastebin.com/rXURRVqW

SE config http://pastebin.com/cFLYVub2
OVPN http://pastebin.com/AsY8H7tW

### PR DESCRIPTION
**Pull request by a-kr**
This pull request implements Individual Certificate Authentication for OpenVPN protocol. This pull request fixes #55.

Client certificate's _Common Name_ is used as username during authentication process. If ``auth-user-pass`` is enabled for OpenVPN client, the password is ignored by server, and username recieved from the client is used instead of the Common Name.

*Note*: only self-signed certificates work presently. CA-signed certificates will not pass verification because OpenSSL library needs to be told where to look for trusted CA certificates, and this feature was not implemented in this pull request. It can be easily added in future, though.

--------

Example:

1. Connect to SoftEther Server via command line client.
2. Create a new user, let's name him **steve**:
```
VPN Server/DEFAULT>UserCreate
UserCreate command - Create User
User Name: steve
Assigned Group Name:
User Full Name:
User Description:
The command completed successfully.
VPN Server/DEFAULT>
```
3. Generate a self-signed certificate for Common Name = steve:
```
VPN Server/DEFAULT>MakeCert
MakeCert command - Create New X.509 Certificate and Private Key (1024 bit)
Name of Certificate to Create (CN): steve
Organization of Certificate to Create (O):
Organization Unit of Certificate to Create (OU):
Country of Certificate to Create (C):
State of Certificate to Create (ST):
Locale of Certificate to Create (L):
Serial Number of Certificate to Create (Hexadecimal):
Expiration Date of Certificate to Create (Days):
File Name to Save Certificate to Create: /tmp/steve.crt
File Name to Save Private Key to Create: /tmp/steve.key
The command completed successfully.
VPN Server/DEFAULT>
```
4. Switch Steve to Individual Certificate Authentication with newly-generated certificate:
```
VPN Server/DEFAULT>UserCertSet
UserCertSet command - Set Individual Certificate Authentication for User Auth Type and Set Certificate
User Name: steve
Read X.509 certificate from file name: /tmp/steve.crt
The command completed successfully.
VPN Server/DEFAULT>
```
5. Dump the Server SSL certificate (ca.crt) to file, and pass this file to Steve, along with his steve.crt and steve.key files:
```
VPN Server>ServerCertGet
ServerCertGet command - Get SSL Certificate of VPN Server
Save X.509 certificate to file name: /tmp/ca.crt

The command completed successfully.

VPN Server>
```
6. Now Steve can use the following OpenVPN client config to connect to SoftEther server:
```
dev tun
proto udp
remote myserver.com 1194
cipher AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3
key steve.key
cert steve.crt
<ca>
# include contents of ca.crt here
</ca>
```
Server log will contain the following lines:
```
2017-05-26 20:47:38.834 OpenVPN Session 1 (10.10.195.127:59213 -> 192.168.56.247:1194): A new session is created. Protocol: UDP
...
2017-05-26 20:47:38.864 OpenVPN Session 1 (10.10.195.127:59213 -> 192.168.56.247:1194) Channel 0: Client certificate received (subject: CN="steve"), will use certificate authentication.
...
2017-05-26 20:47:40.153 [HUB "DEFAULT"] The connection "CID-3" (IP address: 10.10.195.127, Host name: 10.10.195.127, Port number: 59213, Client name: "OpenVPN Client", Version: 4.22, Build: 9634) is attempting to connect to the Virtual Hub. The auth type provided is "OpenVPN certificate authentication" and the user name is "steve".
2017-05-26 20:47:40.153 [HUB "DEFAULT"] The Virtual Hub's Security Account Manager has received the following certificate from the VPN Client and accepted its contents as the certificate for when user "steve" logs in: CN=steve, SERIAL="00" (Digest: MD5="84EAC0F1521A13BF80C51F357A44679B", SHA1="5BB0C832DFA0C4FE043F8390850769CDE261E8F3")
2017-05-26 20:47:40.153 [HUB "DEFAULT"] Connection "CID-3": Successfully authenticated as user "steve".
```
7. If Steve so wishes, he can use the same certificate and key with SoftEther Client instead of OpenVPN client.

--------------------

Regarding Patch Acceptance Policy: I choose option 1.

### CODE REVIEW

**Comment by alexsalex** [comment]
What about ca.crt?
```
Options error: You must define CA file (--ca) or CA path (--capath)
Use --help for more information.
```

**Comment by a-kr** [comment]
ca.crt can be obtained using the command-line client:
```
VPN Server>ServerCertGet
ServerCertGet command - Get SSL Certificate of VPN Server
Save X.509 certificate to file name: /tmp/ca.crt

The command completed successfully.

VPN Server>
```

**Comment by davidebeatrici** [comment]
I would remove commit 2569939a18e262741bd6b5cad3ef3087c5ed6913 from this pull request and propose it in a new one, as it's unrelated.

**Comment by a-kr** [comment]
> I would remove commit 2569939 from this pull request
Done

File: src/Cedar/Interop_OpenVPN.c [hunk 1]
```diff
@@ -780,6 +786,26 @@ void OvsSetupSessionParameters(OPENVPN_SERVER *s, OPENVPN_SESSION *se, OPENVPN_C
...
+		if (c->ClientCert.X->subject_name != NULL)
+		{
+			OvsLog(s, se, c, "LO_CLIENT_CERT", c->ClientCert.X->subject_name->CommonName);
+		}
+		else
+		{
+			OvsLog(s, se, c, "LO_CLIENT_CERT", "(unknown CN)");
+		}
+	}
+	else if (!!c->ClientCert.PreverifyErr)
```
Comment (davidebeatrici) [inline src/Cedar/Interop_OpenVPN.c]: I would flip the logic:
```c++
else if (!c->ClientCert.PreverifyErr)
{
	OvsLog(s, se, c, "LO_CLIENT_NO_CERT");
}
else
{
	OvsLog(s, se, c, "LO_CLIENT_UNVERIFIED_CERT", c->ClientCert.PreverifyErrMessage);
}
```

File: src/Cedar/Protocol.c [hunk 2]
```diff
@@ -2070,6 +2073,7 @@ bool ServerAccept(CONNECTION *c)
 					{
 						// Certificate authentication
 						cert_size = PackGetDataSize(p, "cert");
+
```
Comment (davidebeatrici) [inline src/Cedar/Protocol.c]: Unrelated change.

File: src/Mayaqua/Network.c [hunk 3]
```diff
@@ -5841,7 +5880,9 @@ SSL_PIPE *NewSslPipe(bool server_mode, X *x, K *k, DH_CTX *dh)
 			SSL_CTX_set_ssl_version(ssl_ctx, SSLv23_client_method());
 		}
 
-		//SSL_CTX_set_verify(ssl_ctx, SSL_VERIFY_PEER, cb_test);
+		if (verify_peer) {
```
Comment (davidebeatrici) [inline src/Mayaqua/Network.c]: The bracket should be in a new line, to maintain consistency with the current code style.

File: src/Mayaqua/Network.h [hunk 4]
```diff
@@ -1615,7 +1615,17 @@ void Win32WaitForTubes(TUBE **tubes, UINT num, UINT timeout);
 void UnixWaitForTubes(TUBE **tubes, UINT num, UINT timeout);
 #endif	// OS_WIN32
 
+#define PREVERIFY_ERR_MESSAGE_SIZE 100
+// Info on client certificate collected during TLS handshake
+struct SslClientCertInfo {
+	int PreverifyOk;
```
Comment (davidebeatrici) [inline src/Mayaqua/Network.h]: I would change this into a `bool`.

File: src/Cedar/Interop_OpenVPN.c (hunk 1 above)
Comment (davidebeatrici) [reply src/Cedar/Interop_OpenVPN.c]: Or use `PreverifyOk`:
```c++
else if (c->ClientCert.PreverifyOk)
{
	OvsLog(s, se, c, "LO_CLIENT_NO_CERT");
}
else
{
	OvsLog(s, se, c, "LO_CLIENT_UNVERIFIED_CERT", c->ClientCert.PreverifyErrMessage);
}
```

**Comment by davidebeatrici** [comment]
The new strings should be added to the Traditional Chinese table (**strtable_tw.stb**) as well.

**Comment by a-kr** [comment]
Pushed the fixes in a new commit (068094f)

File: src/Mayaqua/Network.c [hunk 5]
```diff
@@ -5809,14 +5809,53 @@ SOCK *ListenAnyPortEx2(bool local_only, bool disable_ca)
...
+	SSL *ssl;
+	struct SslClientCertInfo *clientcert;
+
+	ssl = X509_STORE_CTX_get_ex_data(ctx, SSL_get_ex_data_X509_STORE_CTX_idx());
+	clientcert = SSL_get_ex_data(ssl, GetSslClientCertIndex());
+
+	if (clientcert != NULL)
+	{
+		clientcert->PreverifyOk = (bool)preverify_ok
;
```
Comment (davidebeatrici) [inline src/Mayaqua/Network.c]: Different line break (**CRLF** instead of **LF**).

Comment (davidebeatrici) [reply src/Mayaqua/Network.c]: I would write an explicit cast:
```c++
clientcert->PreverifyOk = static_cast<bool>(preverify_ok);
```

**Comment by davidebeatrici** [comment]
Is the `PreverifyOk` variable required?

File: src/Mayaqua/Network.c (hunk 5 above)
Comment (a-kr) [reply src/Mayaqua/Network.c]: Fixed the line break, but static_cast would not work here, because Network.c is not complied as a C++ source file:
```
...
cc -DNDEBUG -DVPN_SPEED -DUNIX -DUNIX_LINUX -DCPU_64 -D_REENTRANT -DREENTRANT -D_THREAD_SAFE -D_THREADSAFE -DTHREAD_SAFE -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -I./src/ -I./src/Cedar/ -I./src/Mayaqua/
 -O2 -fsigned-char -m64 -c src/Mayaqua/Network.c -o tmp/objs/Mayaqua/Network.o
src/Mayaqua/Network.c: In function 'SslCertVerifyCallback':
src/Mayaqua/Network.c:5825:29: error: 'static_cast' undeclared (first use in this function)
   clientcert->PreverifyOk = static_cast<bool>(preverify_ok);
```

Comment (a-kr) [reply src/Mayaqua/Network.c]: Removed this line altogether, since, as you correctly noted, the value assigned to PreverifyOk is never used.

**Comment by a-kr** [comment]
`PreverifyOk` was indeed not used; removed it.

File: src/Mayaqua/Network.c (hunk 5 above)
Comment (davidebeatrici) [reply src/Mayaqua/Network.c]: Oh, I didn't notice that it isn't a C++ file, sorry.

**Comment by moatazelmasry2** [comment]
Thank you very much for your patch. It is alot of hard work. And thanks @davidebeatrici  for the review.
There is one (big) problem with this change.  It looks like it is accepting any private key I provide as long at is the same length. 

How to reproduce: Follow your guide in the PR description. Connect to make sure that things are working. then change one or more characters in the key file to any other arbitrary character and try connecting again, it will work

**Comment by moatazelmasry2** [comment]
You are right. I verified this behavior by creating a second valid certificate and using the private key in my client configuration and SoftEther server successfully fails the authentication

**Comment by moatazelmasry2** [comment]
You PR has just been merged into the master branch. As a token of gratitude, your name will be added to the authors lists. Many thanks for your hard work. It is really a great addition to SoftEther.

**Comment by davidebeatrici** [comment]
@a-kr Thank you very much for your contribution!

@moatazelmasry2 I would have squashed the commits, as the second one is a fixup to the first.

**Comment by moatazelmasry2** [comment]
I did squash the commits

**Comment by davidebeatrici** [comment]
Oh, sorry.

I was looking at the commits list in the pull request, as I usually squash them in the source branch and then merge normally.

**Comment by moatazelmasry2** [comment]
But if it is not my repo, then I can not edit it, or?

**Comment by davidebeatrici** [comment]
You can, if the "Allow edits from maintainers." option is enabled, which is by default.

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by davidebeatrici** [comment]
@a-kr Build fails with OpenSSL 1.1.0f:
```cpp
src/Mayaqua/Network.c:5836:11: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
    if (ctx->cert != NULL)
           ^~
```

**Comment by chipitsine** [comment]
seems to be the right time to add openssl-1.1.0 to travis-ci matrix ))

I will add, stay tuned...

**Comment by davidebeatrici** [comment]
Are you planning to use Docker? Or do you prefer to compile the latest version of OpenSSL on Ubuntu 14.04?

**Comment by a-kr** [comment]
I have made a quick fix in #476. It compiles with OpenSSL 1.0.1 (the older one), and _should_ compile with 1.1.0, but I have no access to 1.1.0 at the moment and cannot verify it myself right now. Could you guys please test it with 1.1.0?

**Comment by davidebeatrici** [comment]
Working!

Thank you very much for the fast fix.

**Comment by moatazelmasry2** [comment]
@chipitsine  Please do that
@davidebeatrici  Thanks for the Info

**Comment by davidebeatrici** [comment]
@moatazelmasry2 You're welcome.

**Comment by rav0603** [comment]
When it will be implemented to the stable version(SoftEtherVPN_Stable)?

**Comment by davidebeatrici** [comment]
@DRSDavidSoft It's not implemented in the stable repository yet.

**Comment by DRSDavidSoft** [comment]
@davidebeatrici any active plans to implement it in stable releases yet, or it needs further testing?
Also, is it available in any beta or alpha releases at the moment?

P. S. I appreciate all the work the SoftEther team is doing, the quality of each section of the codes, logic and workflow is quite astonishing.

**Comment by davidebeatrici** [comment]
@DRSDavidSoft The stable repository is managed by @dnobori, we currently don't know when he will update it.

You can download Windows releases compiled from this repository on [AppVeyor](https://ci.appveyor.com/project/SoftEtherVPN/SoftEtherVPN/build/artifacts).

**Comment by DRSDavidSoft** [comment]
@davidebeatrici Thanks for the AppVeyor link, I'll try it out until this PR makes it way into the stable branch.

Out of curiosity, usually what process does it take for a similar PR to be merged into the stable branch by @dnobori? Or is it a bit more irregular and can't be said for sure?
